package auth

import (
		"context"
		"crypto/rand"
		"crypto/sha256"
		"encoding/base64"
		"encoding/hex"
		"errors"
		"fmt"
		"time"

		"github.com/jackc/pgx/v5"
		"github.com/jackc/pgx/v5/pgconn"
		"github.com/jackc/pgx/v5/pgxpool"
	)

// CodeSender obtains a one-time verification code for a phone number and
// delivers it, e.g. by calling the phone and using the last digits of the
// calling number as the code. The code is generated by the sender (not by
// us), since that's how call-based delivery works.
type CodeSender interface {
	RequestCall(ctx context.Context, phone, ip string) (code string, err error)
}

type Service struct {
		pool        *pgxpool.Pool
		sessionDays int
		codeSender  CodeSender
		codeTTL     time.Duration
		resendAfter time.Duration
}

func NewService(pool *pgxpool.Pool, sessionDays int, codeSender CodeSender) *Service {
		return &Service{
					pool:        pool,
					sessionDays: sessionDays,
					codeSender:  codeSender,
					codeTTL:     5 * time.Minute,
					resendAfter: 45 * time.Second,
				}
}

// RequestCode requests a one-time login/registration code for the given
// (already normalized) phone number, delivered by calling it. ip is the
// end user's IP address, used by SMS.ru to rate-limit abusive callers.
func (service *Service) RequestCode(ctx context.Context, phone, ip string) error {
	if phone == "" {
		return errors.New("phone is required")
	}

	var lastRequestedAt time.Time
	err := service.pool.QueryRow(ctx, `
		SELECT created_at FROM otp_codes
			WHERE phone = $1
				ORDER BY created_at DESC
					LIMIT 1
	`, phone).Scan(&lastRequestedAt)
	if err != nil && !isNoRows(err) {
		return fmt.Errorf("check previous code: %w", err)
	}
	if err == nil && time.Since(lastRequestedAt) < service.resendAfter {
		return ErrRequestTooSoon
	}

	var code string
	if service.codeSender != nil {
		code, err = service.codeSender.RequestCall(ctx, phone, ip)
		if err != nil {
			return fmt.Errorf("request call: %w", err)
		}
	} else {
		code, err = GenerateOTPCode()
		if err != nil {
			return fmt.Errorf("generate code: %w", err)
		}
	}

	if _, err := service.pool.Exec(ctx, `
		INSERT INTO otp_codes (phone, purpose, code_hash, expires_at)
			VALUES ($1, 'login', $2, $3)
	`, phone, hashOTPCode(phone, code), time.Now().Add(service.codeTTL)); err != nil {
		return fmt.Errorf("store code: %w", err)
	}

	return nil
}

// VerifyCode checks a one-time code for a phone number. If the phone
// already belongs to a customer, it logs them in. Otherwise it creates a
// new account using registration (FullName and AccountType are required
// for new accounts).
func (service *Service) VerifyCode(
		ctx context.Context,
		phone, code string,
		registration Registration,
		userAgent string,
	) (string, time.Time, error) {
		var codeID int64
		var storedHash string
		var expiresAt time.Time
		var attempts, maxAttempts int
		var consumedAt *time.Time
		err := service.pool.QueryRow(ctx, `
				SELECT id, code_hash, expires_at, attempts, max_attempts, consumed_at
						FROM otp_codes
								WHERE phone = $1
										ORDER BY created_at DESC
												LIMIT 1
													`, phone).Scan(&codeID, &storedHash, &expiresAt, &attempts, &maxAttempts, &consumedAt)
		if isNoRows(err) {
					return "", time.Time{}, ErrInvalidCode
				}
		if err != nil {
					return "", time.Time{}, fmt.Errorf("load code: %w", err)
				}
		if consumedAt != nil || time.Now().After(expiresAt) {
					return "", time.Time{}, ErrInvalidCode
				}
		if attempts >= maxAttempts {
					return "", time.Time{}, ErrTooManyAttempts
				}
		if storedHash != hashOTPCode(phone, code) {
					if _, err := service.pool.Exec(ctx, `
								UPDATE otp_codes SET attempts = attempts + 1 WHERE id = $1
										`, codeID); err != nil {
									return "", time.Time{}, fmt.Errorf("record attempt: %w", err)
								}
					return "", time.Time{}, ErrInvalidCode
				}

		if _, err := service.pool.Exec(ctx, `
				UPDATE otp_codes SET consumed_at = CURRENT_TIMESTAMP WHERE id = $1
					`, codeID); err != nil {
					return "", time.Time{}, fmt.Errorf("consume code: %w", err)
				}

		var customerID int64
		err = service.pool.QueryRow(ctx, `
				SELECT id FROM customers WHERE phone = $1 LIMIT 1
					`, phone).Scan(&customerID)
		if err != nil && !isNoRows(err) {
					return "", time.Time{}, fmt.Errorf("find customer: %w", err)
				}
		if isNoRows(err) {
					customerID, err = service.createCustomer(ctx, phone, registration)
					if err != nil {
									return "", time.Time{}, err
								}
				}

		return service.createSession(ctx, service.pool, customerID, userAgent)
}

// createCustomer creates a new customer record the first time a phone
// number completes OTP verification. FullName and AccountType are
// required; an organization is only created when the customer registered
// as wholesale and actually supplied a company name and INN.
func (service *Service) createCustomer(
		ctx context.Context,
		phone string,
		registration Registration,
	) (int64, error) {
		if registration.FullName == "" ||
			(registration.AccountType != "retail" && registration.AccountType != "wholesale") {
						return 0, ErrRegistrationDetailsRequired
					}

		wholesaleStatus := "not_requested"
		if registration.AccountType == "wholesale" {
					wholesaleStatus = "pending"
				}

		var customerID int64
		err := service.pool.QueryRow(ctx, `
				INSERT INTO customers (
							email, phone, full_name, last_name, patronymic,
										delivery_address, account_type, wholesale_status, consent_at
												)
														VALUES (NULLIF($1, ''), $2, $3, $4, $5, $6, $7, $8, CURRENT_TIMESTAMP)
																RETURNING id
																	`,
									 		registration.Email,
									 		phone,
									 		registration.FullName,
									 		registration.LastName,
									 		registration.Patronymic,
									 		registration.DeliveryAddress,
									 		registration.AccountType,
									 		wholesaleStatus,
									 	).Scan(&customerID)
		if isUniqueViolation(err) {
					if scanErr := service.pool.QueryRow(ctx, `
								SELECT id FROM customers WHERE phone = $1
										`, phone).Scan(&customerID); scanErr == nil {
									return customerID, nil
								}
				}
		if err != nil {
					return 0, fmt.Errorf("insert customer: %w", err)
				}

		if registration.AccountType == "wholesale" &&
			registration.CompanyName != "" && registration.INN != "" {
						var organizationID int64
						err = service.pool.QueryRow(ctx, `
									SELECT id FROM organizations WHERE inn = $1 LIMIT 1
											`, registration.INN).Scan(&organizationID)
						if err != nil && !isNoRows(err) {
										return 0, fmt.Errorf("find organization: %w", err)
									}
						if isNoRows(err) {
										err = service.pool.QueryRow(ctx, `
														INSERT INTO organizations (name, inn, kpp, legal_address)
																		VALUES ($1, $2, NULLIF($3, ''), $4)
																						RETURNING id
																									`, registration.CompanyName, registration.INN, registration.KPP,
																					registration.LegalAddress).Scan(&organizationID)
										if err != nil && !isUniqueViolation(err) {
															return 0, fmt.Errorf("insert organization: %w", err)
														}
									}
						if organizationID != 0 {
										if _, err := service.pool.Exec(ctx, `
														INSERT INTO organization_members (organization_id, customer_id, role)
																		VALUES ($1, $2, 'buyer')
																						ON CONFLICT DO NOTHING
																									`, organizationID, customerID); err != nil {
															return 0, fmt.Errorf("insert organization member: %w", err)
														}
									}
					}

		return customerID, nil
}

func (service *Service) Logout(ctx context.Context, rawToken string) error {
		if rawToken == "" {
					return nil
				}
		if _, err := service.pool.Exec(
					ctx,
					"DELETE FROM auth_sessions WHERE token_hash = $1",
					hashToken(rawToken),
				); err != nil {
					return fmt.Errorf("delete session: %w", err)
				}
		return nil
}

func (service *Service) UserByToken(ctx context.Context, rawToken string) (*User, error) {
		if rawToken == "" {
					return nil, nil
				}

		var user User
		err := service.pool.QueryRow(ctx, `
				SELECT
							c.id, c.email, c.phone, c.full_name, c.last_name, c.patronymic,
										c.delivery_address, c.account_type, c.wholesale_status,
													c.retail_discount_bps
															FROM auth_sessions s
																	JOIN customers c ON c.id = s.customer_id
																			WHERE s.token_hash = $1
																						AND s.expires_at > CURRENT_TIMESTAMP
																									AND c.is_active = TRUE
																											LIMIT 1
																												`, hashToken(rawToken)).Scan(
					&user.ID,
					&user.Email,
					&user.Phone,
					&user.FullName,
					&user.LastName,
					&user.Patronymic,
					&user.DeliveryAddress,
					&user.AccountType,
					&user.WholesaleStatus,
					&user.RetailDiscountBPS,
				)
		if isNoRows(err) {
					return nil, nil
				}
		if err != nil {
					return nil, fmt.Errorf("find session user: %w", err)
				}
		return &user, nil
}

type sessionExecutor interface {
		Exec(context.Context, string, ...any) (pgconn.CommandTag, error)
}

func (service *Service) createSession(
		ctx context.Context,
		executor sessionExecutor,
		customerID int64,
		userAgent string,
	) (string, time.Time, error) {
		randomToken := make([]byte, 32)
		if _, err := rand.Read(randomToken); err != nil {
					return "", time.Time{}, fmt.Errorf("generate session token: %w", err)
				}
		rawToken := base64.RawURLEncoding.EncodeToString(randomToken)
		expiresAt := time.Now().Add(time.Duration(service.sessionDays) * 24 * time.Hour)
		if _, err := executor.Exec(ctx, `
				INSERT INTO auth_sessions (token_hash, customer_id, expires_at, user_agent)
						VALUES ($1, $2, $3, NULLIF($4, ''))
							`, hashToken(rawToken), customerID, expiresAt, truncate(userAgent, 500)); err != nil {
					return "", time.Time{}, fmt.Errorf("insert session: %w", err)
				}
		return rawToken, expiresAt, nil
}

func hashToken(rawToken string) string {
		sum := sha256.Sum256([]byte(rawToken))
		return hex.EncodeToString(sum[:])
}

func isNoRows(err error) bool {
		return err == pgx.ErrNoRows
}

func isUniqueViolation(err error) bool {
		var postgresError *pgconn.PgError
		return err != nil &&
			errors.As(err, &postgresError) &&
			postgresError.Code == "23505"
}

func truncate(value string, maximum int) string {
		runes := []rune(value)
		if len(runes) <= maximum {
					return value
				}
		return string(runes[:maximum])
}
