-- Intentionally no DDL here. The application migration runner executes every
-- file in one transaction before the HTTP server starts. Building indexes on
-- production order history at that point can exceed the platform health-check
-- window and make an otherwise healthy release unavailable.
--
-- The popularity formula remains correct without dedicated indexes. Capacity
-- indexes must be added later with CREATE INDEX CONCURRENTLY by an operational
-- migration that does not block application startup.
