package admin

import("context";"fmt";"os";"testing";"time";"github.com/jackc/pgx/v5/pgxpool")

func TestStage08OfferSnapshotsSelectedQuantitiesAndBoxes(t *testing.T){databaseURL:=os.Getenv("CRM_TEST_DATABASE_URL");if databaseURL==""{t.Skip("CRM_TEST_DATABASE_URL is not set")};ctx:=context.Background();pool,err:=pgxpool.New(ctx,databaseURL);if err!=nil{t.Fatal(err)};defer pool.Close();unique:=time.Now().UnixNano();var customerID,orderID,productID,variantID,itemID int64;_ = pool.QueryRow(ctx,`SELECT id FROM customers WHERE email='crm-owner@example.invalid'`).Scan(&customerID);_ = pool.QueryRow(ctx,`SELECT p.id,pv.id FROM products p JOIN product_variants pv ON pv.product_id=p.id WHERE p.slug='crm-stage07-a'`).Scan(&productID,&variantID);var oldPrice int64;var oldDiscount int;_ = pool.QueryRow(ctx,`SELECT base_price_minor FROM product_variants WHERE id=$1`,variantID).Scan(&oldPrice);_ = pool.QueryRow(ctx,`SELECT retail_discount_bps FROM customers WHERE id=$1`,customerID).Scan(&oldDiscount);if _,err=pool.Exec(ctx,`UPDATE product_variants SET base_price_minor=310000 WHERE id=$1`,variantID);err!=nil{t.Fatal(err)};if _,err=pool.Exec(ctx,`UPDATE customers SET retail_discount_bps=1000 WHERE id=$1`,customerID);err!=nil{t.Fatal(err)};defer func(){_,_=pool.Exec(ctx,`UPDATE product_variants SET base_price_minor=$2 WHERE id=$1`,variantID,oldPrice);_,_=pool.Exec(ctx,`UPDATE customers SET retail_discount_bps=$2 WHERE id=$1`,customerID,oldDiscount)}();if err:=pool.QueryRow(ctx,`INSERT INTO orders(order_number,customer_id,customer_name,phone,email,delivery_method,delivery_fee,subtotal,total,payment_method,payment_status,status,has_preorder) VALUES($1,$2,'Stage 08','+70000000000','stage08@example.invalid','pickup',0,4580,4580,'online','pending','confirmed',1) RETURNING id`,fmt.Sprintf("CRM-S08-A-%d",unique),customerID).Scan(&orderID);err!=nil{t.Fatal(err)};defer func(){_,_=pool.Exec(ctx,`DELETE FROM orders WHERE id=$1`,orderID)}();if err:=pool.QueryRow(ctx,`INSERT INTO order_items(order_id,product_id,variant_id,sku,product_name,variant_label,variant_snapshot,unit_price,quantity,is_preorder,reserved_qty) SELECT $1,$2,$3,sku,'Stage 08 plant',label,'{}',2290,2,1,0 FROM product_variants WHERE id=$3 RETURNING id`,orderID,productID,variantID).Scan(&itemID);err!=nil{t.Fatal(err)}
	repository:=NewPostgresRepository(pool);offer,err:=repository.CreateShipmentOffer(ctx,Actor{CustomerID:customerID,Role:RoleManager},orderID,ShipmentOfferInput{Items:[]ShipmentOfferLineInput{{OrderItemID:itemID,Quantity:1}},Boxes:[]ShipmentBoxInput{{LengthCM:50,WidthCM:20,HeightCM:20,WeightGrams:1200,Contents:[]ShipmentBoxContent{{OrderItemID:itemID,Quantity:1}}}},DeliveryFee:0});if err!=nil{t.Fatal(err)};if offer.Subtotal!=2790||offer.Total!=2790||len(offer.Items)!=1||offer.Items[0].Quantity!=1||offer.Items[0].UnitPrice!=2790||offer.Items[0].OriginalUnitPrice!=2290||len(offer.Boxes)!=1{t.Fatalf("unexpected offer: %+v",offer)};if _,err=pool.Exec(ctx,`UPDATE product_variants SET base_price_minor=400000 WHERE id=$1`,variantID);err!=nil{t.Fatal(err)};saved,err:=repository.ShipmentOffer(ctx,offer.ID);if err!=nil||saved.Items[0].UnitPrice!=2790{t.Fatalf("offer price changed after snapshot: %+v err=%v",saved,err)}
	if _,err:=repository.CreateShipmentOffer(ctx,Actor{CustomerID:customerID,Role:RoleManager},orderID,ShipmentOfferInput{Items:[]ShipmentOfferLineInput{{OrderItemID:itemID,Quantity:1}},Boxes:[]ShipmentBoxInput{{LengthCM:50,WidthCM:20,HeightCM:20,WeightGrams:1200}}});err==nil{t.Fatal("second active offer was created")}
	for _,fulfilled:=range []string{"paid","shipping","shipped","ready","completed"}{
		if _,err=pool.Exec(ctx,`UPDATE shipment_offers SET status=$2 WHERE id=$1`,offer.ID,fulfilled);err!=nil{t.Fatal(err)}
		_,err=repository.CreateShipmentOffer(ctx,Actor{CustomerID:customerID,Role:RoleManager},orderID,ShipmentOfferInput{Items:[]ShipmentOfferLineInput{{OrderItemID:itemID,Quantity:2}},PackagingRequired:true})
		if err==nil{t.Fatalf("allowed already fulfilled units in state %s",fulfilled)}
	}
}
