import { useCallback, useEffect, useState } from "react";
import { api } from "./adminShared";

type AvitoProduct = { id:number; name:string; slug:string; image:string; price:number; stock:number };
type AvitoListing = { itemId:string; title:string; status:string; url:string; remotePrice:number; desiredPublished?:boolean; products:AvitoProduct[] };
type AvitoState = { configured:boolean; publicationEnabled:boolean; feedUrl:string; lastImportAt?:string; lastWorkerAt?:string; lastSuccessAt?:string; lastError:string };

const statusLabel=(status:string)=>({active:"Активное",old:"Архив",blocked:"Заблокировано",rejected:"Отклонённое"}[status.toLowerCase()]||status||"—");

export function AdminAvito({ onError }: { onError:(value:string)=>void }) {
  const [items,setItems]=useState<AvitoListing[]>([]); const [state,setState]=useState<AvitoState|null>(null);
  const [selected,setSelected]=useState<AvitoListing|null>(null); const [query,setQuery]=useState(""); const [results,setResults]=useState<AvitoProduct[]>([]); const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{try{const data=await api<{items:AvitoListing[];state:AvitoState}>("/api/v1/admin/avito");setItems(data.items);setState(data.state);setSelected(previous=>previous?data.items.find(item=>item.itemId===previous.itemId)||null:null)}catch(error){onError((error as Error).message)}},[onError]);
  useEffect(()=>{void load()},[load]);
  useEffect(()=>{if(query.trim().length<2){setResults([]);return}const timer=window.setTimeout(()=>void api<{items:AvitoProduct[]}>(`/api/v1/admin/avito/products?q=${encodeURIComponent(query.trim())}`).then(data=>setResults(data.items)).catch(error=>onError((error as Error).message)),250);return()=>window.clearTimeout(timer)},[query,onError]);
  const importAds=async()=>{setBusy(true);try{await api("/api/v1/admin/avito/import",{method:"POST"});await load()}catch(error){onError((error as Error).message)}finally{setBusy(false)}};
  const togglePublication=async()=>{if(!state)return;setBusy(true);try{await api("/api/v1/admin/avito/publication",{method:"PUT",body:JSON.stringify({enabled:!state.publicationEnabled})});await load()}catch(error){onError((error as Error).message)}finally{setBusy(false)}};
  const save=async(products:AvitoProduct[])=>{if(!selected)return;setBusy(true);try{await api(`/api/v1/admin/avito/${selected.itemId}/products`,{method:"PUT",body:JSON.stringify({productIds:products.map(product=>product.id)})});await load();setSelected({...selected,products})}catch(error){onError((error as Error).message)}finally{setBusy(false)}};
  const add=(product:AvitoProduct)=>{if(selected&&!selected.products.some(item=>item.id===product.id))void save([...selected.products,product]);setQuery("");setResults([])};
  const money=new Intl.NumberFormat("ru-RU",{style:"currency",currency:"RUB",maximumFractionDigits:0});
  return <div className="admin-section admin-avito">
    <div className="admin-heading"><div><p className="eyebrow">Канал продаж</p><h1>Авито</h1><p>Свяжите существующие объявления с одной или несколькими карточками сайта.</p></div><button className="admin-primary" disabled={busy||!state?.configured} onClick={()=>void importAds()}>{busy?"Обновляем…":"Обновить из Авито"}</button></div>
    {!state?.configured&&<div className="admin-message error">Ключи AVITO_CLIENT_ID и AVITO_CLIENT_SECRET не видны приложению.</div>}
    <section className={state?.publicationEnabled?"procurement-checklist ready":"procurement-checklist blocked"}><strong>Правило публикации · {state?.publicationEnabled?"включено":"ожидает подключения автозагрузки"}</strong><p>Если остаток есть хотя бы у одной связанной карточки — объявление должно быть опубликовано. Если остатка нет у всех — снято с публикации.</p><small>Проверка выполняется раз в минуту. Ручное снятие на Авито будет отменено при следующей синхронизации, если товар есть в наличии.</small>{state?.feedUrl&&<small>Адрес для Авито: {state.feedUrl}</small>}<div className="procurement-batch-buttons"><button disabled={busy} onClick={()=>void togglePublication()}>{state?.publicationEnabled?"Приостановить управление":"Включить после настройки Авито"}</button></div></section>
    <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Объявление</th><th>Статус Авито</th><th>Связанные товары</th><th>Остаток</th><th>Цена</th><th></th></tr></thead><tbody>{items.map(item=>{const stock=item.products.reduce((sum,p)=>sum+p.stock,0);const price=Math.min(...item.products.filter(p=>p.stock>0).map(p=>p.price));return <tr key={item.itemId}><td><strong>{item.title||`Объявление ${item.itemId}`}</strong><small>ID {item.itemId}</small></td><td>{statusLabel(item.status)}<small>{item.desiredPublished==null?"Не управляется":item.desiredPublished?"Должно быть опубликовано":"Должно быть снято"}</small></td><td>{item.products.length?item.products.map(p=><small key={p.id}>{p.name}</small>):<span>Не связано</span>}</td><td>{stock}</td><td>{Number.isFinite(price)?money.format(price):money.format(item.remotePrice)}</td><td><button onClick={()=>{setSelected(item);setQuery("")}}>Сопоставить</button></td></tr>})}</tbody></table></div>
    {items.length===0&&<div className="procurement-zero"><strong>Объявления ещё не загружены</strong><span>Нажмите «Обновить из Авито».</span></div>}
    {selected&&<><button className="admin-dialog-backdrop" aria-label="Закрыть" onClick={()=>setSelected(null)}/><div className="admin-dialog" role="dialog" aria-modal="true"><header><div><p className="eyebrow">Avito ID {selected.itemId}</p><h2>{selected.title}</h2></div><button onClick={()=>setSelected(null)}>×</button></header><div className="procurement-candidates">{selected.products.map(product=><article key={product.id}><div><strong>{product.name}</strong><small>Остаток: {product.stock} · {money.format(product.price)}</small></div><button disabled={busy} onClick={()=>void save(selected.products.filter(item=>item.id!==product.id))}>Убрать</button></article>)}</div><label className="procurement-match-search">Добавить карточку сайта<input autoFocus value={query} onChange={event=>setQuery(event.target.value)} placeholder="Введите название товара…"/></label><div className="procurement-candidates">{results.map(product=><article key={product.id}><div><strong>{product.name}</strong><small>Остаток: {product.stock} · {money.format(product.price)}</small></div><button disabled={busy} onClick={()=>add(product)}>Добавить</button></article>)}</div><div className="dialog-actions"><button className="primary" onClick={()=>setSelected(null)}>Готово</button></div></div></>}
  </div>;
}
