import { useEffect, useMemo, useState } from "react";
import { api, money, PageHeading } from "./adminShared";

type ChannelRow={channel:string;revenue:number;orders:number;units:number;returns:number;availability:"data"|"empty"|"no_data"|"unavailable"};
type ProductRow={productId:number;name:string;units:number;revenue:number;returns:number;channels:string[]};
type ExcludedRow={channel:string;sourceDocumentId:string;externalProductId:string;status:string;eventAt:string;reason:string};
type Summary={period:number;periodFrom:string;periodTo:string;channel:string;orders:number;revenue:number;soldUnits:number;averageCheck:number;returns:number;previousRevenue:number;previousOrders:number;daily:Array<{date:string;sessions:number;orders:number;revenue:number}>;salesChannels:ChannelRow[];salesProducts:ProductRow[];dataQuality:{counted:number;duplicates:number;unmatched:number;ambiguous:number;excluded:number;pending:number};excludedSales:ExcludedRow[]};

const channelNames:Record<string,string>={all:"Все каналы",site:"Сайт",saby:"Розница СБИС",wb:"Wildberries",ozon:"Ozon",avito:"Avito"};
const availabilityLabel=(value:ChannelRow["availability"])=>({data:"Есть данные",empty:"Продаж нет",no_data:"Нет данных",unavailable:"Источник недоступен"}[value]);
const change=(current:number,previous:number)=>previous?`${current>=previous?"+":""}${((current-previous)/previous*100).toFixed(1)}% к прошлому периоду`:current?"В прошлом периоде не было данных":"Без изменений";

export function Analytics({onError}:{onError:(message:string)=>void}){
 const [days,setDays]=useState(30);const [channel,setChannel]=useState("all");const [tab,setTab]=useState<"overview"|"products"|"channels">("overview");const [data,setData]=useState<Summary|null>(null);const [loading,setLoading]=useState(true);
 useEffect(()=>{let current=true;api<Summary>(`/api/v1/admin/analytics?days=${days}&channel=${channel}`).then(value=>{if(current){setData(value);setLoading(false)}}).catch(error=>{if(current){setLoading(false);onError(error.message)}});return()=>{current=false}},[days,channel,onError]);
 const maxRevenue=useMemo(()=>Math.max(1,...(data?.daily.map(item=>Math.max(0,item.revenue))||[1])),[data]);const maxChannel=useMemo(()=>Math.max(1,...(data?.salesChannels.map(item=>Math.max(0,item.revenue))||[1])),[data]);
 const attention=(data?.dataQuality.unmatched||0)+(data?.dataQuality.ambiguous||0)+(data?.dataQuality.pending||0);
 return <>
  {attention>0&&<a className="analytics-attention" href="#excluded-sales"><strong>{attention} продаж ожидают сверки</strong><span>Разобрать ↓</span></a>}
  <div className="analytics-heading-row"><PageHeading eyebrow="Продажи без повторов" title="Аналитика продаж" text="Подтверждённые события сайта, СБИС, Ozon и Wildberries в московском времени"/><div className="analytics-controls"><label>Период<select aria-label="Период аналитики" value={days} onChange={event=>{setLoading(true);setDays(Number(event.target.value))}}><option value={7}>7 дней</option><option value={30}>30 дней</option><option value={90}>90 дней</option></select></label><label>Канал<select aria-label="Канал продаж" value={channel} onChange={event=>{setLoading(true);setChannel(event.target.value)}}>{Object.entries(channelNames).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label></div></div>
  <nav className="catalog-tabs analytics-tabs" aria-label="Раздел аналитики">{[["overview","Обзор"],["products","Товары"],["channels","Каналы"]].map(([value,label])=><button type="button" key={value} className={tab===value?"active":""} onClick={()=>setTab(value as typeof tab)}>{label}</button>)}</nav>
  {loading&&!data&&<p className="workspace-empty">Загружаем продажи…</p>}
  {data&&<>
   <p className="analytics-period-note">{data.periodFrom} — {data.periodTo}. Начало и конец суток: Europe/Moscow.</p>
   <div className="admin-stats analytics-sales-kpis"><article><span>Выручка</span><strong>{money.format(data.revenue)}</strong><small>{change(data.revenue,data.previousRevenue)}</small></article><article><span>Заказы</span><strong>{data.orders}</strong><small>{change(data.orders,data.previousOrders)}</small></article><article><span>Средний чек</span><strong>{money.format(data.averageCheck)}</strong><small>до вычета возвратов</small></article><article><span>Продано единиц</span><strong>{data.soldUnits}</strong><small>{data.returns} возвращено</small></article></div>
   {tab==="overview"&&<div className="analytics-overview-grid">
    <section className="admin-block analytics-revenue-chart"><div className="admin-block-heading"><div><p className="eyebrow">Динамика</p><h2>Выручка по дням</h2></div><a href="/admin?section=orders">Перейти в заказы →</a></div><div className="analytics-bars analytics-revenue-bars">{data.daily.map(item=><div key={item.date} title={`${item.date}: ${money.format(item.revenue)}, ${item.orders} заказов`}><i style={{height:`${Math.max(item.revenue?4:0,item.revenue/maxRevenue*100)}%`}}/><small>{new Date(`${item.date}T00:00:00`).toLocaleDateString("ru-RU",{day:"numeric",month:"short"})}</small></div>)}</div></section>
    <section className="admin-block analytics-channel-card"><div className="admin-block-heading"><div><p className="eyebrow">Структура</p><h2>Продажи по каналам</h2></div></div>{data.salesChannels.map(item=><article key={item.channel}><div><strong>{channelNames[item.channel]||item.channel}</strong><span>{item.availability==="data"?money.format(item.revenue):availabilityLabel(item.availability)}</span></div><div className="analytics-channel-track"><i style={{width:item.availability==="data"?`${Math.max(2,item.revenue/maxChannel*100)}%`:"0%"}}/></div></article>)}</section>
    <section className="admin-block analytics-products-table"><div className="admin-block-heading"><div><p className="eyebrow">Товары</p><h2>Продажи товаров</h2></div></div><SalesProducts rows={data.salesProducts.slice(0,8)}/></section>
   </div>}
   {tab==="products"&&<section className="admin-block analytics-block"><div className="admin-block-heading"><div><p className="eyebrow">Товарный итог</p><h2>Все товары периода</h2></div></div><SalesProducts rows={data.salesProducts}/></section>}
   {tab==="channels"&&<section className="admin-block analytics-block"><div className="admin-block-heading"><div><p className="eyebrow">Источники</p><h2>Каналы и доступность</h2></div></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Канал</th><th>Состояние</th><th>Заказы</th><th>Единицы</th><th>Возвраты</th><th>Выручка</th></tr></thead><tbody>{data.salesChannels.map(item=><tr key={item.channel}><td><strong>{channelNames[item.channel]}</strong></td><td>{availabilityLabel(item.availability)}</td><td>{item.availability==="data"?item.orders:"—"}</td><td>{item.availability==="data"?item.units:"—"}</td><td>{item.availability==="data"?item.returns:"—"}</td><td>{item.availability==="data"?money.format(item.revenue):"—"}</td></tr>)}</tbody></table></div></section>}
   <details className="admin-block analytics-definitions"><summary>Как считаются показатели</summary><p><strong>Выручка</strong> — подтверждённые продажи минус возвраты в дату самого события. <strong>Заказ</strong> — уникальный первичный документ продажи. <strong>Средний чек</strong> — сумма подтверждённых продаж до возвратов, делённая на число заказов. <strong>Единицы</strong> — проданные растения минус возвращённые. Неоплаченные заказы, отмены, несопоставленные и неоднозначные строки в итог не входят.</p><p>Одинаковая продажа из СБИС и маркетплейса схлопывается только по общему ключу первичного документа. Без такого ключа строка не объединяется по похожей сумме или времени.</p></details>
   <section className="admin-block analytics-quality" id="excluded-sales"><div className="admin-block-heading"><div><p className="eyebrow">Контроль</p><h2>Качество данных</h2></div><a href="/admin?section=procurement">Аналитика потребности в закупках →</a></div><div className="analytics-quality-counts"><span><b>{data.dataQuality.counted}</b> учтено</span><span><b>{data.dataQuality.duplicates}</b> повторов</span><span><b>{data.dataQuality.unmatched}</b> без товара</span><span><b>{data.dataQuality.ambiguous}</b> неоднозначно</span><span><b>{data.dataQuality.pending}</b> не подтверждено</span></div>{data.excludedSales.length===0?<p className="workspace-empty">Исключённых строк за период нет.</p>:<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Дата</th><th>Канал</th><th>Документ</th><th>Товар источника</th><th>Почему не учтено</th></tr></thead><tbody>{data.excludedSales.map((item,index)=><tr key={`${item.channel}-${item.sourceDocumentId}-${index}`}><td>{item.eventAt}</td><td>{channelNames[item.channel]||item.channel}</td><td>{item.sourceDocumentId||"—"}</td><td>{item.externalProductId}</td><td>{item.reason}</td></tr>)}</tbody></table></div>}</section>
  </>}
 </>;
}

function SalesProducts({rows}:{rows:ProductRow[]}){return <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Товар</th><th>Продано</th><th>Выручка</th><th>Возвраты</th><th>Каналы</th></tr></thead><tbody>{rows.map((item,index)=><tr key={`${item.productId}-${item.name}-${index}`}><td><strong>{item.name}</strong></td><td>{item.units}</td><td>{money.format(item.revenue)}</td><td>{item.returns}</td><td>{item.channels.map(channel=>channelNames[channel]||channel).join(" · ")}</td></tr>)}{rows.length===0&&<tr><td colSpan={5}>За выбранный период подтверждённых продаж нет.</td></tr>}</tbody></table></div>}
