import { useCallback, useEffect, useMemo, useState } from "react";
import { api } from "./adminShared";

type AvitoProduct = { id:number; name:string; slug:string; image:string; price:number; stock:number };
type AvitoListing = { itemId:string; title:string; status:string; url:string; remotePrice:number; desiredPublished?:boolean; lastReconciledAt?:string; lastError:string; products:AvitoProduct[] };
type AvitoState = { configured:boolean; publicationEnabled:boolean; feedUrl:string; lastImportAt?:string; lastWorkerAt?:string; lastSuccessAt?:string; lastError:string };
type ListingFilter = "all"|"attention"|"unlinked"|"out-of-stock"|"mismatch"|"error";

const statusLabel=(status:string)=>({active:"Активное",old:"Архив",blocked:"Заблокировано",rejected:"Отклонённое"}[status.toLowerCase()]||status||"—");
const isActualPublished=(item:AvitoListing)=>item.status.toLowerCase()==="active";
const isManagedStatus=(item:AvitoListing)=>!["blocked","rejected"].includes(item.status.toLowerCase());
const isMismatch=(item:AvitoListing)=>item.desiredPublished!=null&&item.desiredPublished!==isActualPublished(item);
const dateTime=(value?:string)=>value?new Intl.DateTimeFormat("ru-RU",{dateStyle:"short",timeStyle:"short"}).format(new Date(value)):"ещё не было";

export function AdminAvito({ onError }: { onError:(value:string)=>void }) {
  const [items,setItems]=useState<AvitoListing[]>([]); const [state,setState]=useState<AvitoState|null>(null);
  const [selected,setSelected]=useState<AvitoListing|null>(null); const [query,setQuery]=useState(""); const [results,setResults]=useState<AvitoProduct[]>([]); const [busy,setBusy]=useState(false);
  const [search,setSearch]=useState(""); const [filter,setFilter]=useState<ListingFilter>("attention"); const [showEnable,setShowEnable]=useState(false); const [feedConfirmed,setFeedConfirmed]=useState(false);
  const load=useCallback(async()=>{try{const data=await api<{items:AvitoListing[];state:AvitoState}>("/api/v1/admin/avito");setItems(data.items);setState(data.state);setSelected(previous=>previous?data.items.find(item=>item.itemId===previous.itemId)||null:null)}catch(error){onError((error as Error).message)}},[onError]);
  useEffect(()=>{void load()},[load]);
  useEffect(()=>{if(query.trim().length<2){setResults([]);return}const timer=window.setTimeout(()=>void api<{items:AvitoProduct[]}>(`/api/v1/admin/avito/products?q=${encodeURIComponent(query.trim())}`).then(data=>setResults(data.items)).catch(error=>onError((error as Error).message)),250);return()=>window.clearTimeout(timer)},[query,onError]);
  const importAds=async()=>{setBusy(true);try{await api("/api/v1/admin/avito/import",{method:"POST"});await load()}catch(error){onError((error as Error).message)}finally{setBusy(false)}};
  const reconcile=async()=>{setBusy(true);try{await api("/api/v1/admin/avito/reconcile",{method:"POST"});await load()}catch(error){onError((error as Error).message)}finally{setBusy(false)}};
  const togglePublication=async(enabled:boolean)=>{if(!state)return;setBusy(true);try{await api("/api/v1/admin/avito/publication",{method:"PUT",body:JSON.stringify({enabled})});await load();setShowEnable(false);setFeedConfirmed(false)}catch(error){onError((error as Error).message)}finally{setBusy(false)}};
  const save=async(products:AvitoProduct[])=>{if(!selected)return;setBusy(true);try{await api(`/api/v1/admin/avito/${selected.itemId}/products`,{method:"PUT",body:JSON.stringify({productIds:products.map(product=>product.id)})});await load();setSelected({...selected,products})}catch(error){onError((error as Error).message)}finally{setBusy(false)}};
  const add=(product:AvitoProduct)=>{if(selected&&!selected.products.some(item=>item.id===product.id))void save([...selected.products,product]);setQuery("");setResults([])};
  const money=new Intl.NumberFormat("ru-RU",{style:"currency",currency:"RUB",maximumFractionDigits:0});
  const stats=useMemo(()=>({
    active:items.filter(isActualPublished).length,
    unlinked:items.filter(item=>isManagedStatus(item)&&item.products.length===0).length,
    mismatch:items.filter(isMismatch).length,
    errors:items.filter(item=>Boolean(item.lastError)).length,
    outOfStock:items.filter(item=>item.products.length>0&&item.products.every(product=>product.stock<=0)).length,
  }),[items]);
  const attentionCount=items.filter(item=>(isManagedStatus(item)&&item.products.length===0)||isMismatch(item)||Boolean(item.lastError)).length+(state?.lastError?1:0);
  const filtered=useMemo(()=>items.filter(item=>{
    const text=`${item.title} ${item.itemId}`.toLowerCase(); if(search.trim()&&!text.includes(search.trim().toLowerCase()))return false;
    if(filter==="unlinked")return isManagedStatus(item)&&item.products.length===0;
    if(filter==="out-of-stock")return item.products.length>0&&item.products.every(product=>product.stock<=0);
    if(filter==="mismatch")return isMismatch(item);
    if(filter==="error")return Boolean(item.lastError);
    if(filter==="attention")return (isManagedStatus(item)&&item.products.length===0)||isMismatch(item)||Boolean(item.lastError);
    return true;
  }),[filter,items,search]);
  const readyToEnable=Boolean(state?.configured&&state.feedUrl&&state.lastWorkerAt&&items.length>0&&stats.unlinked===0&&!state.lastError&&feedConfirmed);
  const systemHealthy=Boolean(state?.configured&&state.lastSuccessAt&&!state.lastError&&attentionCount===0);
  const filters:{key:ListingFilter;label:string;count:number}[]=[
    {key:"attention",label:"Требуют внимания",count:attentionCount},{key:"all",label:"Все",count:items.length},{key:"unlinked",label:"Без привязки",count:stats.unlinked},
    {key:"out-of-stock",label:"Нет в наличии",count:stats.outOfStock},{key:"mismatch",label:"Не применилось",count:stats.mismatch},{key:"error",label:"Ошибки",count:stats.errors},
  ];
  return <div className="admin-section admin-avito">
    <div className="admin-heading"><div><p className="eyebrow">Канал продаж</p><h1>Авито</h1><p>Контроль публикации существующих объявлений по остаткам сайта.</p></div><div className="avito-heading-actions"><button disabled={busy} onClick={()=>void reconcile()}>{busy?"Проверяем…":"Проверить остатки"}</button><button className="admin-primary" disabled={busy||!state?.configured} onClick={()=>void importAds()}>{busy?"Обновляем…":"Обновить из Авито"}</button></div></div>
    {!state?.configured&&<div className="admin-message error">Ключи AVITO_CLIENT_ID и AVITO_CLIENT_SECRET не видны приложению.</div>}
    <section className={`avito-health ${systemHealthy?"healthy":"attention"}`}><div><span>{systemHealthy?"Контур работает":"Требуется внимание"}</span><strong>{systemHealthy?"Расхождений и ошибок нет":state?.lastError||`${attentionCount} объявлений требуют проверки`}</strong></div><small>Последний успех: {dateTime(state?.lastSuccessAt)}</small></section>
    <div className="admin-stats avito-stats">
      <button onClick={()=>setFilter("all")}><span>Активные</span><strong>{stats.active}</strong><small>сейчас на Авито</small></button>
      <button onClick={()=>setFilter("out-of-stock")} className={stats.outOfStock?"attention":""}><span>Нет в наличии</span><strong>{stats.outOfStock}</strong><small>связанных объявлений</small></button>
      <button onClick={()=>setFilter("unlinked")} className={stats.unlinked?"attention":""}><span>Без привязки</span><strong>{stats.unlinked}</strong><small>нельзя управлять</small></button>
      <button onClick={()=>setFilter("mismatch")} className={stats.mismatch?"attention":""}><span>Не применилось</span><strong>{stats.mismatch}</strong><small>факт не равен правилу</small></button>
    </div>
    <section className={state?.publicationEnabled?"procurement-checklist ready":"procurement-checklist blocked"}><strong>Автоматическое управление · {state?.publicationEnabled?"включено":"выключено"}</strong><p>При наличии хотя бы одной связанной карточки объявление публикуется; при нулевом остатке — уходит в архив.</p><small>Проверка выполняется раз в минуту. Ручное снятие будет отменено при следующей синхронизации, если товар есть в наличии.</small><div className="avito-sync-grid"><span>Импорт с Авито <b>{dateTime(state?.lastImportAt)}</b></span><span>Проверка остатков <b>{dateTime(state?.lastWorkerAt)}</b></span><span>Последний успех <b>{dateTime(state?.lastSuccessAt)}</b></span></div><div className="procurement-batch-buttons">{state?.publicationEnabled?<button disabled={busy} onClick={()=>void togglePublication(false)}>Приостановить управление</button>:<button disabled={busy} onClick={()=>setShowEnable(true)}>Проверить готовность и включить</button>}</div></section>
    <div className="avito-toolbar"><label>Поиск<input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Название или Avito ID"/></label><div className="workspace-filters">{filters.map(item=><button key={item.key} aria-pressed={filter===item.key} onClick={()=>setFilter(item.key)}>{item.label} · {item.count}</button>)}</div></div>
    <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Объявление</th><th>Сейчас / должно быть</th><th>Связанные товары</th><th>Остаток</th><th>Цена</th><th></th></tr></thead><tbody>{filtered.map(item=>{const stock=item.products.reduce((sum,p)=>sum+p.stock,0);const price=Math.min(...item.products.filter(p=>p.stock>0).map(p=>p.price));const mismatch=isMismatch(item);return <tr key={item.itemId} className={mismatch||item.lastError?"avito-row-attention":""}><td><strong>{item.title||`Объявление ${item.itemId}`}</strong><small>ID {item.itemId}{item.url&&<> · <a href={item.url} target="_blank" rel="noreferrer">Открыть на Авито</a></>}</small></td><td><span className="avito-state-pair">{statusLabel(item.status)} → {item.desiredPublished==null?"Не управляется":item.desiredPublished?"Активное":"Архив"}</span>{mismatch&&<small className="avito-warning">Не применилось</small>}{item.lastError&&<small className="avito-warning">{item.lastError}</small>}<small>Проверено: {dateTime(item.lastReconciledAt)}</small></td><td>{item.products.length?item.products.map(p=><small key={p.id}>{p.name}</small>):<span className="avito-warning">Не связано</span>}</td><td>{stock}</td><td>{Number.isFinite(price)?money.format(price):money.format(item.remotePrice)}</td><td><button onClick={()=>{setSelected(item);setQuery("")}}>Сопоставить</button></td></tr>})}</tbody></table></div>
    {filtered.length===0&&<div className="procurement-zero"><strong>{items.length?"По этому фильтру всё чисто":"Объявления ещё не загружены"}</strong><span>{items.length?"Проблемных объявлений не найдено.":"Нажмите «Обновить из Авито»."}</span></div>}
    {showEnable&&<><button className="admin-dialog-backdrop" aria-label="Закрыть" onClick={()=>setShowEnable(false)}/><div className="admin-dialog avito-enable-dialog" role="dialog" aria-modal="true"><header><div><p className="eyebrow">Безопасный запуск</p><h2>Проверка готовности</h2></div><button onClick={()=>setShowEnable(false)}>×</button></header><div className="avito-readiness"><p className={state?.configured?"ready":"blocked"}><b>{state?.configured?"✓":"×"}</b> API-ключи Авито доступны</p><p className={state?.feedUrl?"ready":"blocked"}><b>{state?.feedUrl?"✓":"×"}</b> Защищённый адрес фида создан</p><p className={items.length?"ready":"blocked"}><b>{items.length?"✓":"×"}</b> Объявления импортированы: {items.length}</p><p className={stats.unlinked===0?"ready":"blocked"}><b>{stats.unlinked===0?"✓":"×"}</b> Без привязки: {stats.unlinked}</p><p className={state?.lastWorkerAt?"ready":"blocked"}><b>{state?.lastWorkerAt?"✓":"×"}</b> Остатки рассчитаны</p><p className={!state?.lastError?"ready":"blocked"}><b>{!state?.lastError?"✓":"×"}</b> Ошибок синхронизации нет</p></div>{state?.feedUrl&&<div className="avito-feed-address"><small>Адрес для автозагрузки Avito</small><code>{state.feedUrl}</code></div>}<div className="avito-preview"><strong>После включения</strong><span>{items.filter(item=>item.desiredPublished===true).length} будут опубликованы</span><span>{items.filter(item=>item.desiredPublished===false).length} уйдут в архив</span></div><label className="avito-confirm"><input type="checkbox" checked={feedConfirmed} onChange={event=>setFeedConfirmed(event.target.checked)}/> Я подключил этот фид в автозагрузке Avito и понимаю, какие объявления изменятся.</label><div className="dialog-actions"><button onClick={()=>setShowEnable(false)}>Отмена</button><button className="primary" disabled={!readyToEnable||busy} onClick={()=>void togglePublication(true)}>Включить управление</button></div></div></>}
    {selected&&<><button className="admin-dialog-backdrop" aria-label="Закрыть" onClick={()=>setSelected(null)}/><div className="admin-dialog" role="dialog" aria-modal="true"><header><div><p className="eyebrow">Avito ID {selected.itemId}</p><h2>{selected.title}</h2></div><button onClick={()=>setSelected(null)}>×</button></header><div className="procurement-candidates">{selected.products.map(product=><article key={product.id}><div><strong>{product.name}</strong><small>Остаток: {product.stock} · {money.format(product.price)}</small></div><button disabled={busy} onClick={()=>void save(selected.products.filter(item=>item.id!==product.id))}>Убрать</button></article>)}</div><label className="procurement-match-search">Добавить карточку сайта<input autoFocus value={query} onChange={event=>setQuery(event.target.value)} placeholder="Введите название товара…"/></label><div className="procurement-candidates">{results.map(product=><article key={product.id}><div><strong>{product.name}</strong><small>Остаток: {product.stock} · {money.format(product.price)}</small></div><button disabled={busy} onClick={()=>add(product)}>Добавить</button></article>)}</div><div className="dialog-actions"><button className="primary" onClick={()=>setSelected(null)}>Готово</button></div></div></>}
  </div>;
}
