import { useCallback, useEffect, useState } from "react";
import { api, money, PageHeading } from "./adminShared";
import type { FinanceImport, FinanceOverview, FinanceTransaction } from "./adminTypes";
import "./styles/admin-finance.css";

const banks:Record<string,string>={tochka:"Точка",sber:"Сбер",ozon:"Ozon Bank"};
const classes:Record<string,[string,string]>={sale:["Продажа","income"],marketplace_payout:["Выплата маркетплейса","income"],acquiring:["Эквайринг","income"],commission:["Комиссия","expense"],supplier:["Поставщик","expense"],tax:["Налог","expense"],own_transfer:["Между своими счетами","none"],loan_principal:["Тело займа","none"],loan_interest:["Проценты по займу","expense"],owner_contribution:["Вклад владельца","none"],owner_withdrawal:["Вывод владельцу","none"],other:["Прочее","expense"],review:["Не разобрано","review"]};

export function AdminFinance({onError}:{onError:(message:string)=>void}){
 const [data,setData]=useState<FinanceOverview>();const [tab,setTab]=useState<"operations"|"import"|"cash">("operations");const [busy,setBusy]=useState(false);
 const load=useCallback(()=>api<FinanceOverview>("/api/v1/admin/finance").then(setData).catch(e=>onError(e instanceof Error?e.message:"Не удалось загрузить финансы")),[onError]);useEffect(()=>{void load()},[load]);
 const transactions=data?.transactions||[];const imports=data?.imports||[];const cash=data?.cash||[];
 const balance=(data?.income||0)-(data?.expense||0);const confirmed=transactions.filter(x=>x.confirmed);
 const classify=async(item:FinanceTransaction,value:string)=>{const meta=classes[value]||classes.review;setBusy(true);try{await api(`/api/v1/admin/finance/transactions/${item.id}`,{method:"PATCH",body:JSON.stringify({classification:value,pnlEffect:meta[1],reason:"Изменено владельцем"})});await load()}catch(e){onError(e instanceof Error?e.message:"Не удалось сохранить статью")}finally{setBusy(false)}};
 return <div className="finance-workspace"><div className="finance-heading"><PageHeading eyebrow="Бизнес · с 1 сентября 2026" title="Финансы" text="Банковские выписки, разбор операций и наличная касса в одном журнале."/><button className="primary" onClick={()=>setTab("import")}>+ Загрузить выписку</button></div>
 <section className="finance-metrics"><article><span>Доходы</span><strong>{money.format(data?.income||0)}</strong><small>подтверждённые операции</small></article><article><span>Расходы</span><strong>{money.format(data?.expense||0)}</strong><small>без переводов между своими</small></article><article><span>Результат</span><strong>{money.format(balance)}</strong><small>до себестоимости и начислений</small></article><article className={(data?.reviewCount||0)>0?"attention":""}><span>Требуют разбора</span><strong>{data?.reviewCount||0}</strong><small>операций без статьи</small></article></section>
 <nav className="finance-tabs"><button className={tab==="operations"?"active":""} onClick={()=>setTab("operations")}>Операции <b>{confirmed.length}</b></button><button className={tab==="import"?"active":""} onClick={()=>setTab("import")}>Импорт <b>{imports.length}</b></button><button className={tab==="cash"?"active":""} onClick={()=>setTab("cash")}>Касса <b>{money.format(data?.cashBalance||0)}</b></button></nav>
 {tab==="operations"&&<Operations items={transactions} busy={busy} onClassify={classify}/>} {tab==="import"&&<Imports items={imports} busy={busy} setBusy={setBusy} reload={load} onError={onError}/>} {tab==="cash"&&<Cash items={cash} balance={data?.cashBalance||0} busy={busy} setBusy={setBusy} reload={load} onError={onError}/>}</div>
}

function Operations({items,busy,onClassify}:{items:FinanceTransaction[];busy:boolean;onClassify:(item:FinanceTransaction,value:string)=>void}){return <section className="finance-panel"><header><div><h3>Журнал операций</h3><p>Переводы между своими счетами не влияют на P&amp;L.</p></div><label className="finance-search">⌕ <input placeholder="Найти контрагента или назначение"/></label></header><div className="finance-table"><div className="finance-row finance-labels"><span>Дата</span><span>Контрагент и назначение</span><span>Банк</span><span>Статья</span><span>Сумма</span></div>{items.map(item=><div className={`finance-row ${item.classification==="review"?"needs-review":""}`} key={item.id}><time>{new Date(`${item.operationDate}T00:00:00`).toLocaleDateString("ru-RU",{day:"2-digit",month:"short"})}</time><div><strong>{item.counterparty||"Контрагент не указан"}</strong><small>{item.purpose||"В краткой выписке нет назначения"}</small></div><span>{banks[item.bank]||item.bank}</span><select disabled={busy} value={item.classification} onChange={e=>void onClassify(item,e.target.value)}>{Object.entries(classes).map(([value,meta])=><option value={value} key={value}>{meta[0]}</option>)}</select><b className={item.credit>0?"income":"expense"}>{item.credit>0?"+":"−"}{money.format(item.credit||item.debit)}</b></div>)}{!items.length&&<p className="finance-empty">Загрузите первую выписку.</p>}</div></section>}

function Imports({items,busy,setBusy,reload,onError}:{items:FinanceImport[];busy:boolean;setBusy:(v:boolean)=>void;reload:()=>Promise<void>;onError:(s:string)=>void}){const [bank,setBank]=useState("tochka");const [account,setAccount]=useState("");const [file,setFile]=useState<File>();const upload=async(e:React.FormEvent)=>{e.preventDefault();if(!file)return;const form=new FormData();form.append("bank",bank);form.append("accountNumber",account);form.append("file",file);setBusy(true);try{await api("/api/v1/admin/finance/imports/preview",{method:"POST",body:form});setFile(undefined);await reload()}catch(err){onError(err instanceof Error?err.message:"Не удалось разобрать выписку")}finally{setBusy(false)}};const confirm=async(id:number)=>{setBusy(true);try{await api(`/api/v1/admin/finance/imports/${id}/confirm`,{method:"POST"});await reload()}catch(err){onError(err instanceof Error?err.message:"Не удалось подтвердить импорт")}finally{setBusy(false)}};return <div className="finance-import-layout"><form className="finance-panel finance-upload" onSubmit={upload}><h3>Новая выписка</h3><p>Сначала покажем новые строки, дубли и операции для ручного разбора.</p><label>Банк<select value={bank} onChange={e=>setBank(e.target.value)}>{Object.entries(banks).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Номер счёта<input value={account} onChange={e=>setAccount(e.target.value)} placeholder="Можно оставить пустым"/></label><label className="finance-file"><input type="file" accept=".pdf,.xlsx" onChange={e=>setFile(e.target.files?.[0])}/><b>{file?.name||"Выбрать PDF или XLSX"}</b><small>до 25 МБ</small></label><button className="primary" disabled={busy||!file}>{busy?"Разбираем…":"Проверить выписку"}</button></form><section className="finance-panel finance-imports"><h3>История импорта</h3>{items.map(item=><article key={item.id}><div><strong>{banks[item.bank]} · {item.fileName}</strong><small>{item.rowsNew} новых · {item.rowsDuplicate} дублей · {item.rowsReview} разобрать</small></div>{item.status==="preview"?<button disabled={busy} onClick={()=>void confirm(item.id)}>Подтвердить</button>:<em>Принято</em>}</article>)}{!items.length&&<p className="finance-empty">История пока пуста.</p>}</section></div>}

function Cash({items,balance,busy,setBusy,reload,onError}:{items:FinanceOverview["cash"];balance:number;busy:boolean;setBusy:(v:boolean)=>void;reload:()=>Promise<void>;onError:(s:string)=>void}){const [kind,setKind]=useState("expense");const [direction,setDirection]=useState<"in"|"out">("out");const [amount,setAmount]=useState(0);const [purpose,setPurpose]=useState("");const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await api("/api/v1/admin/finance/cash",{method:"POST",body:JSON.stringify({operationDate:new Date().toISOString().slice(0,10),kind,direction,amount,purpose})});setAmount(0);setPurpose("");await reload()}catch(err){onError(err instanceof Error?err.message:"Не удалось добавить операцию")}finally{setBusy(false)}};return <div className="finance-cash-layout"><section className="finance-panel cash-balance"><span>Расчётный остаток</span><strong>{money.format(balance)}</strong><p>Продажи из СБИС и ручные движения. Внесение в банк связывается как перевод.</p></section><form className="finance-panel cash-form" onSubmit={submit}><h3>Добавить движение</h3><div><label>Операция<select value={kind} onChange={e=>setKind(e.target.value)}><option value="expense">Расход</option><option value="opening">Начальный остаток</option><option value="bank_transfer">Внесение в банк</option><option value="adjustment">Корректировка</option></select></label><label>Направление<select value={direction} onChange={e=>setDirection(e.target.value as "in"|"out")}><option value="out">Из кассы</option><option value="in">В кассу</option></select></label></div><label>Сумма<input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label><label>Комментарий<input value={purpose} onChange={e=>setPurpose(e.target.value)}/></label><button className="primary" disabled={busy||amount<=0}>Добавить</button></form><section className="finance-panel cash-history"><h3>Последние движения</h3>{(items||[]).map(item=><article key={item.id}><time>{new Date(`${item.operationDate}T00:00:00`).toLocaleDateString("ru-RU")}</time><span>{item.purpose||item.kind}</span><b className={item.direction==="in"?"income":"expense"}>{item.direction==="in"?"+":"−"}{money.format(item.amount)}</b></article>)}</section></div>}
