import { useEffect, useMemo, useState } from "react";
import type { ProductReview } from "./types";
import { stars } from "./types";

const ratingLabels = ["", "Плохо", "Есть проблемы", "Нормально", "Хорошо", "Отлично"];
const filePayload = (file: File) => new Promise<{ contentType: string; data: string }>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve({ contentType: file.type, data: String(reader.result).split(",")[1] || "" }); reader.onerror = reject; reader.readAsDataURL(file); });

export function ReviewComposer({ slug, rating, count }: { slug: string; rating: number; count: number }) {
  const [selected, setSelected] = useState(0); const [hovered,setHovered]=useState(0); const [open,setOpen]=useState(false); const [text,setText]=useState(""); const [media,setMedia]=useState<File[]>([]); const [notice,setNotice]=useState(""); const [submitted,setSubmitted]=useState(false); const [sending,setSending]=useState(false);
  const previews=useMemo(()=>media.map((file)=>({file,url:URL.createObjectURL(file)})),[media]);
  useEffect(()=>()=>previews.forEach(({url})=>URL.revokeObjectURL(url)),[previews]);
  useEffect(()=>{if(!open)return;const key=(event:KeyboardEvent)=>{if(event.key==="Escape")setOpen(false)};document.addEventListener("keydown",key);document.body.classList.add("modal-open");return()=>{document.removeEventListener("keydown",key);document.body.classList.remove("modal-open")}},[open]);
  const choose=(value:number)=>{setSelected(value);setHovered(0);setOpen(true);setNotice("");setSubmitted(false)};
  const addMedia=(files:FileList|null)=>{const accepted=Array.from(files||[]).filter((file)=>file.type.startsWith("image/")||file.type==="video/mp4"||file.type==="video/webm");const next=[...media,...accepted].slice(0,4);if(next.filter((file)=>file.type.startsWith("video/")).length>1){setNotice("Можно прикрепить одно видео");return}if(next.some((file)=>file.type.startsWith("image/")&&file.size>5*1024*1024)||next.some((file)=>file.type.startsWith("video/")&&file.size>20*1024*1024)){setNotice("Фото — до 5 МБ, видео — до 20 МБ");return}setMedia(next);setNotice("")};
  const submit=async()=>{setSending(true);setNotice("");try{const photos=await Promise.all(media.map(filePayload));const response=await fetch(`/api/v1/products/${encodeURIComponent(slug)}/reviews`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({rating:selected,text,photos})});const body=await response.json() as {error?:string};if(!response.ok)throw new Error(body.error||"Не удалось отправить отзыв");setText("");setMedia([]);setOpen(false);setSubmitted(true)}catch(error){setNotice(error instanceof Error?error.message:"Не удалось отправить отзыв")}finally{setSending(false)}};
  const shown=hovered||selected||Math.round(rating);
  return <div className="purchase-review"><div className="purchase-review-stars" role="radiogroup" aria-label="Поставить оценку" onMouseLeave={()=>setHovered(0)}>{[1,2,3,4,5].map((value)=><button type="button" role="radio" aria-checked={selected===value} aria-label={`${value} из 5`} className={value<=shown?"active":""} onMouseEnter={()=>setHovered(value)} onFocus={()=>setHovered(value)} onBlur={()=>setHovered(0)} onClick={()=>choose(value)} key={value}>★</button>)}</div><button className="purchase-review-meta" type="button" onClick={()=>document.querySelector("#reviews")?.scrollIntoView({behavior:"smooth"})}>{count?`${rating.toFixed(1)} · ${count} отзывов`:"Пока без отзывов"}</button>{hovered>0&&<span className="purchase-review-hint">{ratingLabels[hovered]} — нажмите, чтобы написать отзыв</span>}{submitted&&<p className="review-submit-success" role="status">Спасибо за отзыв.</p>}
    {open&&<div className="review-modal" role="dialog" aria-modal="true" aria-labelledby="review-modal-title" onMouseDown={(event)=>{if(event.target===event.currentTarget)setOpen(false)}}><form onSubmit={(event)=>{event.preventDefault();void submit()}}><header><div><span>{stars(selected)}</span><h2 id="review-modal-title">{ratingLabels[selected]}</h2><p>Расскажите о растении и доставке</p></div><button type="button" onClick={()=>setOpen(false)} aria-label="Закрыть">×</button></header><label htmlFor="review-modal-text">Ваш отзыв</label><textarea id="review-modal-text" autoFocus required minLength={10} maxLength={3000} rows={6} value={text} onChange={(event)=>setText(event.target.value)} placeholder="В каком состоянии приехало растение? Как прошло получение?" />{previews.length>0&&<div className="review-media-preview">{previews.map(({file,url},index)=><figure key={`${file.name}-${file.lastModified}`}>{file.type.startsWith("video/")?<video src={url} controls preload="metadata"/>:<img src={url} alt="Предпросмотр"/>}<button type="button" onClick={()=>setMedia((current)=>current.filter((_,itemIndex)=>itemIndex!==index))} aria-label={`Удалить ${file.name}`}>×</button></figure>)}</div>}<div className="review-modal-actions"><label className="review-media-button"><input type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" multiple onChange={(event)=>{addMedia(event.target.files);event.currentTarget.value=""}}/><span>＋</span>Добавить фото или видео</label><button type="submit" disabled={sending}>{sending?"Отправляем…":"Отправить отзыв"}</button></div><small>До 4 файлов, одно видео. Перед публикацией отзыв проверит сотрудник магазина.</small>{notice&&<p className="review-form-notice" role="alert">{notice}</p>}</form></div>}
  </div>;
}

export function ProductReviews({ reviews }: { reviews: ProductReview[] }) {
  const [sort,setSort]=useState<"new"|"high"|"low">("new");const sorted=useMemo(()=>[...reviews].sort((left,right)=>sort==="high"?right.rating-left.rating:sort==="low"?left.rating-right.rating:new Date(right.date).getTime()-new Date(left.date).getTime()),[reviews,sort]);
  return <section className="pdp-reviews pdp-section pdp-info-card" id="reviews"><header className="pdp-section-heading"><div><p className="eyebrow">Опыт покупателей</p><h2>Отзывы покупателей</h2></div>{reviews.length>1&&<label className="review-sort">Сортировка<select value={sort} onChange={(event)=>setSort(event.target.value as typeof sort)}><option value="new">Сначала новые</option><option value="high">С высокой оценкой</option><option value="low">С низкой оценкой</option></select></label>}</header><div className="review-feed">{sorted.length?sorted.map((review)=>{const items=review.media?.length?review.media:review.photos.map((url)=>({url,contentType:"image/jpeg"}));return <article key={review.id}><header><div><strong>{review.author}</strong>{review.verifiedPurchase&&<small>Подтверждённая покупка</small>}</div><div><span>{stars(review.rating)}</span><time dateTime={review.date}>{new Date(review.date).toLocaleDateString("ru-RU")}</time></div></header><p>{review.text}</p>{items.length>0&&<div className="review-photos">{items.map((item)=>item.contentType.startsWith("video/")?<video key={item.url} src={item.url} controls preload="metadata"/>:<img key={item.url} src={item.url} alt="Фото растения от покупателя" loading="lazy"/>)}</div>}</article>}):<div className="reviews-empty"><strong>Здесь пока тихо</strong><p>После получения заказа оцените растение звёздами в блоке покупки.</p></div>}</div></section>;
}
